pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'cd /home/faisal/Fluxus/FluxusUI'
                sh 'git checkout deploy_07162023_local'
                sh 'git pull'
                sh 'ng build --configuration production'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}