pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'git pull'
                sh 'docker build -f /home/faisal/Fluxus/FluxusUI/pipeline/Dockerfile -t fluxus-ui .'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'sudo docker run -d --rm -p 80:80 fluxus-ui'
            }
        }
    }
}