// AUTO-GENERATED by scripts/build-image-variants.mjs — do not hand-edit.
// Re-run via `npm run build:image-variants`.

/**
 * Maps a source image path to the variant widths generated for it.
 * Consumed by the responsive IMAGE_LOADER to rewrite NgOptimizedImage
 * srcset entries to the nearest available variant. Images absent here are
 * served as-is (the loader returns the original src untouched).
 */
export const IMAGE_VARIANTS: Record<string, readonly number[]> = {
  'assets/images/blog/fresh-css-deploy/cover.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/homelab-storage/hardware-stack.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/homelab-storage/nvme-collage.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/homelab-storage/ugreen-ups.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/homelab-storage/wd-red-collage.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/motion-audit/cover.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/observability-pipeline/cover.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/outcome-durability/cover.webp': [256, 384, 640, 960, 1280],
  'assets/images/blog/self-healing-guardrails/cover.webp': [256, 384, 640, 960, 1280],
  'assets/images/portfolio/BacktrackingSearch.webp': [256, 384],
  'assets/images/portfolio/BookStore.webp': [256, 384, 640, 960, 1280],
  'assets/images/portfolio/DictionaryApp.webp': [256, 384, 640],
  'assets/images/portfolio/ImageGeneratorAI.webp': [256, 384, 640, 960],
  'assets/images/portfolio/InsecureFileExtraction.webp': [256, 384, 640],
  'assets/images/portfolio/JenkinsCICD.webp': [256, 384, 640],
  'assets/images/portfolio/TextAnalyzerAI.webp': [256, 384, 640, 960],
};
