import { IMAGE_DIMS } from '@core/services/image-dims.generated';

/**
 * Look up the intrinsic `{ w, h }` for an image referenced by a markdown
 * body or a post cover, from the build-time map generated by
 * `scripts/build-image-dims.mjs`. Returns `undefined` for absolute
 * (`http(s):`) URLs (never in the map) and for unknown paths; callers layer
 * their own fallback (e.g. a 16:9 placeholder) so the layout still reserves
 * space and avoids CLS.
 *
 * Accepts the path shapes that appear in posts:
 *   - `assets/images/blog/foo.webp`   (recommended, exact key)
 *   - `/assets/images/blog/foo.webp`  (root-relative)
 *   - `./assets/images/blog/foo.webp` (relative)
 */
export function lookupImageDims(href: string): { w: number; h: number } | undefined {
  if (!href) return undefined;
  if (/^https?:/i.test(href)) return undefined;
  const trimmed = href.replace(/^\.?\/?/, '');
  return IMAGE_DIMS[trimmed];
}
