import type { ApplicationConfig } from '@angular/core';
import {
  ErrorHandler,
  provideBrowserGlobalErrorListeners,
  provideAppInitializer,
  provideZonelessChangeDetection,
  inject,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling, withViewTransitions } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { provideClientHydration, withIncrementalHydration } from '@angular/platform-browser';
import { provideServiceWorker } from '@angular/service-worker';
import { routes } from './app.routes';
import { provideResponsiveImageLoader } from './core/image/responsive-image-loader';
import { SeoService } from './core/services/seo.service';
import { AppErrorHandler } from './core/services/app-error-handler';
import { WebVitalsService } from './core/services/web-vitals.service';
import { AppUpdateService } from './core/services/app-update.service';
import { environment } from '@env/environment';

/**
 * Run an app-initializer body defensively: a throw inside `provideAppInitializer`
 * aborts the whole bootstrap (blank page), which is far worse than the feature
 * that initializer powers being degraded. SEO meta, web-vitals reporting and the
 * update poller are all non-essential to first render, so a failure is logged
 * (and forwarded to the global ErrorHandler when available) but never fatal.
 */
function safeInitializer(label: string, run: () => void): void {
  try {
    run();
  } catch (err) {
    try {
      inject(ErrorHandler).handleError(err);
    } catch {
      console.error(`[appInitializer] ${label} failed during bootstrap:`, err);
    }
  }
}

export const appConfig: ApplicationConfig = {
  providers: [
    // Zoneless is the v21 default (no zone.js polyfill is loaded), but we
    // declare it explicitly so future contributors don't accidentally
    // re-introduce zone change detection by adding zone.js to polyfills.
    provideZonelessChangeDetection(),
    provideBrowserGlobalErrorListeners(),
    provideRouter(
      routes,
      withViewTransitions(),
      // anchorScrolling makes [routerLink][fragment] actually scroll to the
      // matching id; scrollPositionRestoration restores prior position on
      // back/forward navigation. Required for the in-page TOC to work.
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
    // fetch is the default backend as of v22 (withFetch was deprecated); the
    // SSR + httpResource paths rely on it.
    provideHttpClient(),
    // Maps NgOptimizedImage srcset entries to pre-generated WebP width
    // variants (scripts/build-image-variants.mjs); images without variants
    // pass through untouched. See ./core/image/responsive-image-loader.
    provideResponsiveImageLoader(),
    // withIncrementalHydration enables event replay automatically and lets
    // `@defer` blocks above the fold avoid hydration layout shift.
    provideClientHydration(withIncrementalHydration()),
    provideAppInitializer(() => {
      const seo = inject(SeoService);
      safeInitializer('SeoService', () => seo.init());
    }),
    provideAppInitializer(() => {
      // Fire-and-forget — `WebVitalsService.start()` schedules its work on
      // `requestIdleCallback`, so this returns synchronously and never blocks
      // bootstrap or the LCP frame.
      const vitals = inject(WebVitalsService);
      safeInitializer('WebVitalsService', () => vitals.start());
    }),
    provideAppInitializer(() => {
      // AppUpdateService listens for SW version updates AND polls the
      // build-time /version.json stamp, then reloads the live tab at the
      // next safe boundary (idle / next routerLink / tab refocus). Inert
      // under SSR. Initialising at bootstrap (rather than on first route)
      // means the version-stamp baseline check fires within the first
      // few seconds of every visit, so even users who land on a single
      // page and bounce get the fresh assets if a deploy is mid-flight.
      const appUpdate = inject(AppUpdateService);
      safeInitializer('AppUpdateService', () => appUpdate.init());
    }),
    { provide: ErrorHandler, useClass: AppErrorHandler },
    // Register the service worker generated by @angular/service-worker. Only
    // enabled in production builds — the dev server doesn't ship ngsw-worker.
    //
    // `registerWhenStable:5000` (down from the previous 30s) shortens the
    // window where a fresh visit could miss a just-deployed SW manifest:
    // typical blog-post visits are 30-90 s, so a 30 s registration delay
    // meant the SW often never even tried to detect a new version before
    // the user navigated away. 5 s still defers past the `stable` event
    // (so LCP isn't contended) but lands the registration well within the
    // first scroll's worth of reading time.
    provideServiceWorker('ngsw-worker.js', {
      enabled: environment.production,
      registrationStrategy: 'registerWhenStable:5000',
    }),
  ],
};
