import {
  ApplicationConfig,
  ErrorHandler,
  provideBrowserGlobalErrorListeners,
  provideAppInitializer,
  provideZonelessChangeDetection,
  inject,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling, withViewTransitions } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideClientHydration, withIncrementalHydration } from '@angular/platform-browser';
import { provideServiceWorker } from '@angular/service-worker';
import { routes } from './app.routes';
import { SeoService } from './core/services/seo.service';
import { AppErrorHandler } from './core/services/app-error-handler';
import { WebVitalsService } from './core/services/web-vitals.service';
import { AppUpdateService } from './core/services/app-update.service';
import { environment } from '@env/environment';

export const appConfig: ApplicationConfig = {
  providers: [
    // Zoneless is the v21 default (no zone.js polyfill is loaded), but we
    // declare it explicitly so future contributors don't accidentally
    // re-introduce zone change detection by adding zone.js to polyfills.
    provideZonelessChangeDetection(),
    provideBrowserGlobalErrorListeners(),
    provideRouter(
      routes,
      withViewTransitions(),
      // anchorScrolling makes [routerLink][fragment] actually scroll to the
      // matching id; scrollPositionRestoration restores prior position on
      // back/forward navigation. Required for the in-page TOC to work.
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
    provideHttpClient(withFetch()),
    // withIncrementalHydration enables event replay automatically and lets
    // `@defer` blocks above the fold avoid hydration layout shift.
    provideClientHydration(withIncrementalHydration()),
    provideAppInitializer(() => inject(SeoService).init()),
    provideAppInitializer(() => {
      // Fire-and-forget — `WebVitalsService.start()` schedules its work on
      // `requestIdleCallback`, so this returns synchronously and never blocks
      // bootstrap or the LCP frame.
      inject(WebVitalsService).start();
    }),
    provideAppInitializer(() => {
      // AppUpdateService listens for SW version updates AND polls the
      // build-time /version.json stamp, then reloads the live tab at the
      // next safe boundary (idle / next routerLink / tab refocus). Inert
      // under SSR. Initialising at bootstrap (rather than on first route)
      // means the version-stamp baseline check fires within the first
      // few seconds of every visit, so even users who land on a single
      // page and bounce get the fresh assets if a deploy is mid-flight.
      inject(AppUpdateService).init();
    }),
    { provide: ErrorHandler, useClass: AppErrorHandler },
    // Register the service worker generated by @angular/service-worker. Only
    // enabled in production builds — the dev server doesn't ship ngsw-worker.
    //
    // `registerWhenStable:5000` (down from the previous 30s) shortens the
    // window where a fresh visit could miss a just-deployed SW manifest:
    // typical blog-post visits are 30-90 s, so a 30 s registration delay
    // meant the SW often never even tried to detect a new version before
    // the user navigated away. 5 s still defers past the `stable` event
    // (so LCP isn't contended) but lands the registration well within the
    // first scroll's worth of reading time.
    provideServiceWorker('ngsw-worker.js', {
      enabled: environment.production,
      registrationStrategy: 'registerWhenStable:5000',
    }),
  ],
};
