import {
  ApplicationConfig,
  ErrorHandler,
  provideBrowserGlobalErrorListeners,
  provideAppInitializer,
  provideZonelessChangeDetection,
  inject,
} from '@angular/core';
import { provideRouter, withInMemoryScrolling, withViewTransitions } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideClientHydration, withIncrementalHydration } from '@angular/platform-browser';
import { provideServiceWorker } from '@angular/service-worker';
import { routes } from './app.routes';
import { SeoService } from './core/services/seo.service';
import { AppErrorHandler } from './core/services/app-error-handler';
import { WebVitalsService } from './core/services/web-vitals.service';
import { environment } from '@env/environment';

export const appConfig: ApplicationConfig = {
  providers: [
    // Zoneless is the v21 default (no zone.js polyfill is loaded), but we
    // declare it explicitly so future contributors don't accidentally
    // re-introduce zone change detection by adding zone.js to polyfills.
    provideZonelessChangeDetection(),
    provideBrowserGlobalErrorListeners(),
    provideRouter(
      routes,
      withViewTransitions(),
      // anchorScrolling makes [routerLink][fragment] actually scroll to the
      // matching id; scrollPositionRestoration restores prior position on
      // back/forward navigation. Required for the in-page TOC to work.
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
    provideHttpClient(withFetch()),
    // withIncrementalHydration enables event replay automatically and lets
    // `@defer` blocks above the fold avoid hydration layout shift.
    provideClientHydration(withIncrementalHydration()),
    provideAppInitializer(() => inject(SeoService).init()),
    provideAppInitializer(() => {
      // Fire-and-forget — `WebVitalsService.start()` schedules its work on
      // `requestIdleCallback`, so this returns synchronously and never blocks
      // bootstrap or the LCP frame.
      inject(WebVitalsService).start();
    }),
    { provide: ErrorHandler, useClass: AppErrorHandler },
    // Register the service worker generated by @angular/service-worker. Only
    // enabled in production builds — the dev server doesn't ship ngsw-worker.
    provideServiceWorker('ngsw-worker.js', {
      enabled: environment.production,
      registrationStrategy: 'registerWhenStable:30000',
    }),
  ],
};
