#!/usr/bin/env node
/**
 * Reads every prerendered HTML file under `dist/fluxus/browser`, computes a
 * SHA-256 hash for each unique inline `<script>` body, and writes a fresh
 * `dist/fluxus/security-headers.conf` that allowlists exactly that set
 * (theme pre-paint, JSON-LD, Angular event-replay/jsaction bootstrap, etc.).
 *
 * The Dockerfile copies the generated file into the runtime image, so the
 * production CSP never needs `'unsafe-inline'` for scripts.
 *
 * Run via `npm run build:prod` (chained after `inject-meta.mjs`).
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const DIST_HTML = join(process.cwd(), 'dist/fluxus/browser');
const OUT_DIR = join(process.cwd(), 'dist/fluxus');
const OUT_FILE = join(OUT_DIR, 'security-headers.conf');

if (!statSync(DIST_HTML, { throwIfNoEntry: false })?.isDirectory()) {
  console.error(`dist/fluxus/browser/ does not exist — run \`ng build\` first.`);
  process.exit(1);
}

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) yield* walk(full);
    else if (name.endsWith('.html')) yield full;
  }
}

const SCRIPT_TAG = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;

function isInline(attrs) {
  // External script (has src=) — handled by `'self'`, no hash needed.
  return !/\bsrc\s*=/i.test(attrs);
}

const hashes = new Set();

for (const file of walk(DIST_HTML)) {
  const html = readFileSync(file, 'utf-8');
  for (const match of html.matchAll(SCRIPT_TAG)) {
    const [, attrs, body] = match;
    if (!isInline(attrs)) continue;
    if (!body) continue;
    const digest = createHash('sha256').update(body, 'utf-8').digest('base64');
    hashes.add(`'sha256-${digest}'`);
  }
}

const sortedHashes = Array.from(hashes).sort();

const conf = `# AUTO-GENERATED by scripts/build-csp.mjs at build time. Do not hand-edit.
# Sources every inline <script> hash from the prerendered HTML so the
# script-src directive can stay strict (no 'unsafe-inline').
#
# style-src still keeps 'unsafe-inline' because Angular's prerender emits
# many short-lived <style> blocks per route — moving those off-document is a
# larger refactor (extract-css build option).

add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header Content-Security-Policy "default-src 'self'; script-src 'self' ${sortedHashes.join(
  ' ',
)}; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';" always;
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, conf, 'utf-8');
console.log(
  `Wrote ${OUT_FILE} with ${sortedHashes.length} inline-script hash${
    sortedHashes.length === 1 ? '' : 'es'
  }.`,
);
