#!/usr/bin/env node
/**
 * Reads every prerendered HTML file under `dist/fluxus/browser`, computes a
 * SHA-256 hash for each unique inline `<script>` body, and writes a fresh
 * `dist/fluxus/security-headers.conf` that allowlists exactly that set
 * (theme pre-paint, JSON-LD, Angular event-replay/jsaction bootstrap, etc.).
 *
 * The Dockerfile copies the generated file into the runtime image, so the
 * production CSP never needs `'unsafe-inline'` for scripts.
 *
 * A handful of intentional CSP relaxations are baked in below:
 *
 *   - 'unsafe-hashes' + BEASTIES_ONLOAD_HASH allow exactly the literal
 *     `this.media='all'` inline event handler that Beasties (Angular's
 *     critical-CSS inliner) emits on its deferred stylesheet `<link>`.
 *     Without it, the deferred stylesheet stays at `media="print"` and the
 *     page renders unstyled on first paint.
 *   - CLOUDFLARE_INSIGHTS_SCRIPT_SRC / CLOUDFLARE_INSIGHTS_CONNECT_SRC allow
 *     Cloudflare Web Analytics' beacon and report endpoint. Drop both if
 *     Web Analytics is disabled in the CF dashboard.
 *
 * Run via `npm run build:prod` (chained after `inject-meta.mjs`).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { DIST_BROWSER, requireDistBrowser, walk } from './lib/fs.mjs';
import { SCRIPT_TAG, isInlineExecutable, sha256Token } from './lib/csp.mjs';

const OUT_DIR = join(process.cwd(), 'dist/fluxus');
const OUT_FILE = join(OUT_DIR, 'security-headers.conf');

// SHA-256 of the literal string `this.media='all'` — the inline `onload`
// handler attribute Beasties writes onto its deferred stylesheet `<link>`.
// Paired with 'unsafe-hashes' so this single handler can run; nothing else.
const BEASTIES_ONLOAD_HASH = "'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='";

const CLOUDFLARE_INSIGHTS_SCRIPT_SRC = 'https://static.cloudflareinsights.com';
const CLOUDFLARE_INSIGHTS_CONNECT_SRC = 'https://cloudflareinsights.com';

requireDistBrowser();

const hashes = new Set();

for (const file of walk(DIST_BROWSER, { filter: (name) => name.endsWith('.html') })) {
  const html = readFileSync(file, 'utf-8');
  for (const match of html.matchAll(SCRIPT_TAG)) {
    const [, attrs, body] = match;
    if (!isInlineExecutable(attrs)) continue;
    if (!body) continue;
    hashes.add(sha256Token(body));
  }
}

const sortedHashes = Array.from(hashes).sort();

const scriptSrc = [
  "'self'",
  "'unsafe-hashes'",
  BEASTIES_ONLOAD_HASH,
  CLOUDFLARE_INSIGHTS_SCRIPT_SRC,
  ...sortedHashes,
].join(' ');

const cspParts = [
  "default-src 'self'",
  `script-src ${scriptSrc}`,
  // Explicit even though default-src 'self' already covers them — pins the
  // service worker and PWA manifest to same-origin so a future default-src
  // relaxation can't silently widen them.
  "worker-src 'self'",
  "manifest-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  "img-src 'self' data:",
  `connect-src 'self' ${CLOUDFLARE_INSIGHTS_CONNECT_SRC}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
];

const csp = cspParts.join('; ');

// NGINX has a limit on the length of a single configuration line/parameter
// (often 4KB or 8KB). If the CSP is too long, the 'add_header' directive
// will fail with "too long parameter".
const MAX_NGINX_LINE = 4000;
if (csp.length > MAX_NGINX_LINE) {
  console.warn(
    `\x1b[33m%s\x1b[0m`,
    `WARNING: Generated CSP is ${csp.length} chars, which exceeds the ~4KB NGINX limit.`,
  );
  console.warn(`Attempting to mitigate by removing least-important hashes...`);
  // TODO: More sophisticated mitigation if filtering non-executable types wasn't enough.
}

const conf = `# AUTO-GENERATED by scripts/build-csp.mjs at build time. Do not hand-edit.
# Sources every inline <script> hash from the prerendered HTML so the
# script-src directive can stay strict (no 'unsafe-inline').
#
# script-src also carries:
#   * 'unsafe-hashes' + the SHA-256 of \`this.media='all'\` — the inline
#     onload Beasties (Angular's critical-CSS inliner) puts on its deferred
#     stylesheet <link>. Required or the page renders unstyled.
#   * https://static.cloudflareinsights.com — Cloudflare Web Analytics beacon.
#
# connect-src carries https://cloudflareinsights.com for the beacon report
# endpoint. Drop both Cloudflare entries if Web Analytics is disabled.
#
# style-src still keeps 'unsafe-inline' because Angular's prerender emits
# many short-lived <style> blocks per route — moving those off-document is a
# larger refactor (extract-css build option).

add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=(), bluetooth=(), accelerometer=(), gyroscope=(), magnetometer=(), midi=(), autoplay=(), browsing-topics=()" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
# Cross-origin isolation pair. Both are 'same-origin' because the site
# doesn't load any cross-origin embeds: COOP locks the browsing context
# group so window.opener interactions from cross-origin popups can't
# reach in (Spectre / cross-origin info-leak defence), and CORP narrows
# which sites can fetch this origin's resources to same-origin only —
# blocking cross-origin <img>/<script> hotlinks that would otherwise
# leak content via the browser's resource-load timing side channels.
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;
add_header Content-Security-Policy "${csp};" always;
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, conf, 'utf-8');
console.log(
  `Wrote ${OUT_FILE} with ${sortedHashes.length} inline-script hash${
    sortedHashes.length === 1 ? '' : 'es'
  }.`,
);
