#!/usr/bin/env node
/**
 * Reads every prerendered HTML file under `dist/fluxus/browser`, computes a
 * SHA-256 hash for each unique inline `<script>` body, and writes a fresh
 * `dist/fluxus/security-headers.conf` that allowlists exactly that set
 * (theme pre-paint, JSON-LD, Angular event-replay/jsaction bootstrap, etc.).
 *
 * The Dockerfile copies the generated file into the runtime image, so the
 * production CSP never needs `'unsafe-inline'` for scripts.
 *
 * A handful of intentional CSP relaxations are baked in below:
 *
 *   - 'unsafe-hashes' + BEASTIES_ONLOAD_HASH allow exactly the literal
 *     `this.media='all'` inline event handler that Beasties (Angular's
 *     critical-CSS inliner) emits on its deferred stylesheet `<link>`.
 *     Without it, the deferred stylesheet stays at `media="print"` and the
 *     page renders unstyled on first paint.
 *   - CLOUDFLARE_INSIGHTS_SCRIPT_SRC / CLOUDFLARE_INSIGHTS_CONNECT_SRC allow
 *     Cloudflare Web Analytics' beacon and report endpoint. Drop both if
 *     Web Analytics is disabled in the CF dashboard.
 *
 * Run via `npm run build:prod` (chained after `inject-meta.mjs`).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { DIST_BROWSER, requireDistBrowser, walk } from './lib/fs.mjs';
import { SCRIPT_TAG, isInlineExecutable, sha256Token, MAX_NGINX_LINE } from './lib/csp.mjs';
import { STATIC_SECURITY_HEADERS } from './lib/headers.mjs';

const OUT_DIR = join(process.cwd(), 'dist/fluxus');
const OUT_FILE = join(OUT_DIR, 'security-headers.conf');

// SHA-256 of the literal string `this.media='all'` — the inline `onload`
// handler attribute Beasties writes onto its deferred stylesheet `<link>`.
// Paired with 'unsafe-hashes' so this single handler can run; nothing else.
const BEASTIES_ONLOAD_HASH = "'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='";

const CLOUDFLARE_INSIGHTS_SCRIPT_SRC = 'https://static.cloudflareinsights.com';
const CLOUDFLARE_INSIGHTS_CONNECT_SRC = 'https://cloudflareinsights.com';

requireDistBrowser();

const hashes = new Set();

for (const file of walk(DIST_BROWSER, { filter: (name) => name.endsWith('.html') })) {
  const html = readFileSync(file, 'utf-8');
  for (const match of html.matchAll(SCRIPT_TAG)) {
    const [, attrs, body] = match;
    if (!isInlineExecutable(attrs)) continue;
    if (!body) continue;
    hashes.add(sha256Token(body));
  }
}

const sortedHashes = Array.from(hashes).sort();

const scriptSrc = [
  "'self'",
  "'unsafe-hashes'",
  BEASTIES_ONLOAD_HASH,
  CLOUDFLARE_INSIGHTS_SCRIPT_SRC,
  ...sortedHashes,
].join(' ');

const cspParts = [
  "default-src 'self'",
  `script-src ${scriptSrc}`,
  // Explicit even though default-src 'self' already covers them — pins the
  // service worker and PWA manifest to same-origin so a future default-src
  // relaxation can't silently widen them.
  "worker-src 'self'",
  "manifest-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  "img-src 'self' data:",
  `connect-src 'self' ${CLOUDFLARE_INSIGHTS_CONNECT_SRC}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
];

const csp = cspParts.join('; ');

// NGINX rejects an over-long `add_header` parameter and fails OPEN — it drops
// the directive entirely, shipping the site with no CSP. That must never pass
// silently, so an overflow is a hard build failure rather than a warning. If
// this ever trips, the fix is to trim the script-src allowlist (e.g. fewer
// distinct inline-script shapes in the prerender) — NOT to raise the ceiling
// past what NGINX accepts. audit-csp.mjs re-checks the same limit downstream.
if (csp.length > MAX_NGINX_LINE) {
  console.error(
    `\x1b[31m✗ build-csp: generated CSP is ${csp.length} chars, exceeding the ${MAX_NGINX_LINE}-char NGINX limit.\x1b[0m`,
  );
  console.error(
    `  NGINX would drop the add_header directive and serve NO Content-Security-Policy. ` +
      `Trim the script-src allowlist (reduce distinct inline-script shapes) before deploying.`,
  );
  process.exit(1);
}

const conf = `# AUTO-GENERATED by scripts/build-csp.mjs at build time. Do not hand-edit.
# Sources every inline <script> hash from the prerendered HTML so the
# script-src directive can stay strict (no 'unsafe-inline').
#
# script-src also carries:
#   * 'unsafe-hashes' + the SHA-256 of \`this.media='all'\` — the inline
#     onload Beasties (Angular's critical-CSS inliner) puts on its deferred
#     stylesheet <link>. Required or the page renders unstyled.
#   * https://static.cloudflareinsights.com — Cloudflare Web Analytics beacon.
#
# connect-src carries https://cloudflareinsights.com for the beacon report
# endpoint. Drop both Cloudflare entries if Web Analytics is disabled.
#
# style-src still keeps 'unsafe-inline' because Angular's prerender emits
# many short-lived <style> blocks per route — moving those off-document is a
# larger refactor (extract-css build option).

${STATIC_SECURITY_HEADERS}
add_header Content-Security-Policy "${csp};" always;
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, conf, 'utf-8');
console.log(
  `Wrote ${OUT_FILE} with ${sortedHashes.length} inline-script hash${
    sortedHashes.length === 1 ? '' : 'es'
  }.`,
);
